# Generated by Django 6.0 on 2026-04-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_unique_choice_text_per_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('event', models.CharField(db_index=True, max_length=32)),
                ('change_from', models.TextField(blank=True, default='')),
                ('change_to', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['model', 'event'], name='polls_audit_model_944dcd_idx'), models.Index(fields=['user', '-created_at'], name='polls_audit_user_id_efe21f_idx')],
            },
        ),
    ]
